// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

/// <reference types="@cloudflare/workers-types" />

interface CloudflareEnv {
  cloudmark: KVNamespace;
}

declare module 'h3' {
  interface H3EventContext {
    cloudflare?: {
      env: CloudflareEnv;
      ctx: ExecutionContext;
    };
  }
}
